### ISSUE TITLE
Time varying error in scoring function

### ISSUE THREAD

**Issue by jk-brown** [JGCRI/matilda#75]
Notes:

1. There is a difference in varying error in `score_bayesian()` and time-vary error in `RMSE_calc()`. This means introducing `sigma` into `RMSE_calc()` and programming to accept a vector, it also forces a change in the `sigma` argument name in `score_bayesian()`.

2. If the goal is to time-vary error I think the solution is to add a sigma value to `RMSE_calc()`. This would be programmed to have default `sigma = sd(observed_data)`, otherwise the user can supply a vector of error values for `sigma` but must be the same length as the observed data. This provides an option for introducing time-varying error when RMSE values are computed. 

3. Varying `sigma` in `score_bayesian()` does not have the same effect because it varies `sigma` in the likelihood function. This will not time-vary error but rather vary error among models, thereby introducing variation in the likelihood sensitivity to increasing RMSE values (i.e., with this change, some models with high RMSE can be computed as having high likelihood). I don't think this is the effect we want. Keeping `sigma` a single value in the likelihood calculation ensures a consistent down-weighting of models as RMSE increases, while still giving users the ability to manipulate this sensitivity (over all the models). 

Solution as I see it based on the Notes above: in order to have both pieces of the functionality (time-varying error and likelihood sensitivity) we should introduce `sigma` to `RMSE_calc()`.

This means that the `sigma` argument in `score_bayesian()` will be applied internally to `RMSE_calc()`. This forces a new argument in `score_bayesian()` we can call `sensitivity` which introduces a sensitivity of the likelihood weights to increasing RMSE values - the best way forward will be to change the argument to a multiplier applied to the `sd` of the scoring criterion being used (`sensitivity = 1` -> 1 * sd(obs_data) or `sensitivity = 4` -> 4 * sd(obs_data).) 

Tasks to adjust the code:

- [x] change `RMSE_calc` to accept a `sigma` value that can be varied with each year of the observed data.
- [x] default `sigma = NULL` -> sd(observed_data)? Not sure if this makes sense - currently no sigma in `RMSE_calc()`
- [x] if user provides a vector of sigma values, apply those values to `sigma` - stop if the vector is not of required length (must be same length as the observed data being used for the RMSE calculation.
- [x] change argument naming scheme in `score_bayesian()` what is current `sigma` change to `sensitivity` (more accurate representation of functionality).
- [x] `sensitivity` will be a multiplier applied to "sigma" in the likelihood formula - defaults to 1.

These changes are being made in the `enhancement/time-varying-error` branch

**Comment by bpbond** [comment]
Well laid out and looks reasonable! Let me know if I can help.
